package formatrunner

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunCheckThenWriteThenCheck(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "main.go")
	mustWrite(t, file, `package sample

func buildMessage( enabled bool ) string {
	if !enabled {
		return "disabled"
	}
	values := map[string]string{"first_key": "first_value", "second_key": "second_value", "third_key": "third_value", "fourth_key": "fourth_value", "fifth_key": "fifth_value", "sixth_key": "sixth_value"}
	return values["first_key"]
}
`)

	checkResult, err := Run(Options{
		Mode:          Check,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err == nil {
		t.Fatal("Run(Check) error = nil, want formatting failure")
	}

	if len(checkResult.ChangedFiles) == 0 {
		t.Fatalf("Run(Check) changed files = 0, want fixture file")
	}

	writeResult, err := Run(Options{
		Mode:          Write,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err != nil {
		t.Fatalf("Run(Write) error = %v", err)
	}

	if len(writeResult.ChangedFiles) == 0 {
		t.Fatalf("Run(Write) changed files = 0, want fixture file")
	}

	formatted, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read formatted file: %v", err)
	}

	for _, expected := range []string{
		"func buildMessage(enabled bool) string",
		"return \"disabled\"\n\t}\n\n\tvalues :=",
	} {
		if !strings.Contains(string(formatted), expected) {
			t.Fatalf("formatted output missing %q:\n%s", expected, formatted)
		}
	}

	cleanResult, err := Run(Options{
		Mode:          Check,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err != nil {
		t.Fatalf("Run(Check clean) error = %v", err)
	}

	if len(cleanResult.ChangedFiles) != 0 {
		t.Fatalf("Run(Check clean) changed files = %#v, want none", cleanResult.ChangedFiles)
	}
}

func TestRunSkipsVendorAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	generated := filepath.Join(root, "generated.go")
	vendorFile := filepath.Join(root, "vendor", "pkg", "bad.go")

	mustWrite(t, generated, `// Code generated by test. DO NOT EDIT.
package sample

func generated(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)
	mustWrite(t, vendorFile, `package pkg

func bad( value string ) string { return value }
`)

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{root},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err != nil {
		t.Fatalf("Run(Check) error = %v", err)
	}

	if len(result.CheckedFiles) != 0 {
		t.Fatalf("CheckedFiles = %#v, want no generated/vendor files", result.CheckedFiles)
	}
}

func TestRunAcceptsGoStyleRecursivePath(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "pkg", "main.go")
	mustWrite(t, file, `package pkg

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{filepath.Join(root, "...")},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check ./...) error = nil, want formatting failure")
	}

	if len(result.CheckedFiles) != 1 {
		t.Fatalf("CheckedFiles = %#v, want one file", result.CheckedFiles)
	}
}

func TestRunChecksExplicitCurrentDirectory(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "main.go"), `package p

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	t.Cleanup(func() {
		if err := os.Chdir(originalDir); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	})
	if err := os.Chdir(root); err != nil {
		t.Fatalf("chdir %s: %v", root, err)
	}

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{"."},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check .) error = nil, want formatting failure")
	}

	if len(result.CheckedFiles) != 1 {
		t.Fatalf("CheckedFiles = %#v, want current directory file", result.CheckedFiles)
	}
}

func mustWrite(t *testing.T, path string, body string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
