package formatrunner

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestRunCheckThenWriteThenCheck(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "main.go")
	mustWrite(t, file, `package sample

func buildMessage( enabled bool ) string {
	if !enabled {
		return "disabled"
	}
	values := map[string]string{"first_key": "first_value", "second_key": "second_value", "third_key": "third_value", "fourth_key": "fourth_value", "fifth_key": "fifth_value", "sixth_key": "sixth_value"}
	return values["first_key"]
}
`)

	checkResult, err := Run(Options{
		Mode:          Check,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err == nil {
		t.Fatal("Run(Check) error = nil, want formatting failure")
	}

	if len(checkResult.ChangedFiles) == 0 {
		t.Fatalf("Run(Check) changed files = 0, want fixture file")
	}

	writeResult, err := Run(Options{
		Mode:          Write,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err != nil {
		t.Fatalf("Run(Write) error = %v", err)
	}

	if len(writeResult.ChangedFiles) == 0 {
		t.Fatalf("Run(Write) changed files = 0, want fixture file")
	}

	formatted, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read formatted file: %v", err)
	}

	for _, expected := range []string{
		"func buildMessage(enabled bool) string",
		"return \"disabled\"\n\t}\n\n\tvalues :=",
	} {
		if !strings.Contains(string(formatted), expected) {
			t.Fatalf("formatted output missing %q:\n%s", expected, formatted)
		}
	}

	cleanResult, err := Run(Options{
		Mode:          Check,
		Paths:         []string{root},
		MaxLen:        80,
		GoToolchain:   "local",
		SkipGoLines:   true,
		DiffMaxBytes:  1 << 20,
		IncludeHidden: false,
	})
	if err != nil {
		t.Fatalf("Run(Check clean) error = %v", err)
	}

	if len(cleanResult.ChangedFiles) != 0 {
		t.Fatalf("Run(Check clean) changed files = %#v, want none", cleanResult.ChangedFiles)
	}
}

func TestRunSkipsVendorAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	generated := filepath.Join(root, "generated.go")
	vendorFile := filepath.Join(root, "vendor", "pkg", "bad.go")

	mustWrite(t, generated, `// Code generated by test. DO NOT EDIT.
package sample

func generated(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)
	mustWrite(t, vendorFile, `package pkg

func bad( value string ) string { return value }
`)

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{root},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err != nil {
		t.Fatalf("Run(Check) error = %v", err)
	}

	if len(result.CheckedFiles) != 0 {
		t.Fatalf("CheckedFiles = %#v, want no generated/vendor files", result.CheckedFiles)
	}
}

func TestRunAcceptsGoStyleRecursivePath(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "pkg", "main.go")
	mustWrite(t, file, `package pkg

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{filepath.Join(root, "...")},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check ./...) error = nil, want formatting failure")
	}

	if len(result.CheckedFiles) != 1 {
		t.Fatalf("CheckedFiles = %#v, want one file", result.CheckedFiles)
	}
}

func TestRunChecksExplicitCurrentDirectory(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "main.go"), `package p

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	t.Cleanup(func() {
		if err := os.Chdir(originalDir); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	})

	if err := os.Chdir(root); err != nil {
		t.Fatalf("chdir %s: %v", root, err)
	}

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{"."},
		GoToolchain:  "local",
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check .) error = nil, want formatting failure")
	}

	if len(result.CheckedFiles) != 1 {
		t.Fatalf("CheckedFiles = %#v, want current directory file", result.CheckedFiles)
	}
}

func TestRunReportsProgressForEachFile(t *testing.T) {
	root := t.TempDir()
	first := filepath.Join(root, "a.go")
	second := filepath.Join(root, "b.go")

	mustWrite(t, first, `package sample

func first() string {
	return "first"
}
`)
	mustWrite(t, second, `package sample

func second() string {
	return "second"
}
`)

	var events []ProgressEvent

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{root},
		GoToolchain:  "local",
		Jobs:         1,
		SkipGoLines:  true,
		DiffMaxBytes: 1 << 20,
		Progress: func(event ProgressEvent) {
			events = append(events, event)
		},
	})
	if err != nil {
		t.Fatalf("Run(Check) error = %v", err)
	}

	if len(result.CheckedFiles) != 2 {
		t.Fatalf("CheckedFiles = %#v, want two files", result.CheckedFiles)
	}

	if len(events) != 3 {
		t.Fatalf("progress events = %#v, want two file events and a done event", events)
	}

	expectedFiles := []string{first, second}

	for i, expectedFile := range expectedFiles {
		if events[i].Current != i+1 || events[i].Total != 2 || events[i].File != expectedFile || events[i].Done {
			t.Fatalf("progress event %d = %#v, want current file %q", i, events[i], expectedFile)
		}
	}

	done := events[len(events)-1]

	if done.Current != 2 || done.Total != 2 || done.File != "" || !done.Done {
		t.Fatalf("done progress event = %#v, want completed progress", done)
	}
}

func TestFormatSourceCanSkipReadabilityPass(t *testing.T) {
	input := []byte(`package sample

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	output, issues, err := FormatSource("sample.go", input, Options{
		GoToolchain:     "local",
		SkipGoLines:     true,
		SkipReadability: true,
	})
	if err != nil {
		t.Fatalf("FormatSource error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("issues = %#v, want none when readability pass is skipped", issues)
	}

	if strings.Contains(string(output), "return false\n\t}\n\n\treturn true") {
		t.Fatalf("output included readability blank line despite SkipReadability:\n%s", output)
	}
}

func TestRunCheckCanSkipDiffGeneration(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "main.go")
	mustWrite(t, file, `package sample

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{root},
		GoToolchain:  "local",
		Jobs:         1,
		SkipGoLines:  true,
		Diff:         false,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check) error = nil, want formatting failure")
	}

	if !reflect.DeepEqual(result.ChangedFiles, []string{file}) {
		t.Fatalf("ChangedFiles = %#v, want %#v", result.ChangedFiles, []string{file})
	}

	if result.Diff != "" {
		t.Fatalf("Diff = %q, want empty when Diff is false", result.Diff)
	}
}

func TestRunParallelResultsAreDeterministic(t *testing.T) {
	root := t.TempDir()
	files := []string{
		filepath.Join(root, "a.go"),
		filepath.Join(root, "b.go"),
		filepath.Join(root, "c.go"),
	}

	for _, file := range files {
		mustWrite(t, file, `package sample

func active(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)
	}

	result, err := Run(Options{
		Mode:         Check,
		Paths:        []string{root},
		GoToolchain:  "local",
		Jobs:         4,
		SkipGoLines:  true,
		Diff:         true,
		DiffMaxBytes: 1 << 20,
	})
	if err == nil {
		t.Fatal("Run(Check) error = nil, want formatting failure")
	}

	if !reflect.DeepEqual(result.CheckedFiles, files) {
		t.Fatalf("CheckedFiles = %#v, want %#v", result.CheckedFiles, files)
	}

	if !reflect.DeepEqual(result.ChangedFiles, files) {
		t.Fatalf("ChangedFiles = %#v, want %#v", result.ChangedFiles, files)
	}

	previous := -1

	for _, file := range files {
		current := strings.Index(result.Diff, "--- "+file)

		if current < 0 {
			t.Fatalf("Diff missing header for %s:\n%s", file, result.Diff)
		}

		if current <= previous {
			t.Fatalf("Diff order is not deterministic for %s:\n%s", file, result.Diff)
		}

		previous = current
	}

	for idx, issue := range result.Issues {
		if idx > 0 && issue.File < result.Issues[idx-1].File {
			t.Fatalf("Issues out of file order: %#v", result.Issues)
		}
	}
}

func TestFormatSourceUsesExistingCachedGolinesBinary(t *testing.T) {
	cacheRoot := t.TempDir()
	binDir := filepath.Join(cacheRoot, "golines", GolinesVersion)

	if err := os.MkdirAll(binDir, 0o755); err != nil {
		t.Fatalf("mkdir golines cache: %v", err)
	}

	marker := filepath.Join(cacheRoot, "used")
	binPath := filepath.Join(binDir, golinesBinaryName())
	script := "#!/bin/sh\n" +
		"printf used > " + shellQuote(marker) + "\n" +
		"while [ \"$#\" -gt 0 ]; do shift; done\n" +
		"cat\n"

	if err := os.WriteFile(binPath, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake golines binary: %v", err)
	}

	_, _, err := FormatSource("sample.go", []byte(`package sample

func value() string {
	return "ok"
}
`), Options{
		MaxLen:          80,
		GoToolchain:     "local",
		SkipReadability: true,
		golinesCacheDir: cacheRoot,
	})
	if err != nil {
		t.Fatalf("FormatSource error = %v", err)
	}

	if _, err := os.Stat(marker); err != nil {
		t.Fatalf("cached golines binary was not used: %v", err)
	}
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func mustWrite(t *testing.T, path string, body string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
