package mutate

import (
	"strings"
	"testing"
)

func TestRewriteAppliesSafeMutations(t *testing.T) {
	input := `package sample

import "fmt"

type Config struct{}

func load() error {
	if err := read(); err != nil {
		return fmt.Errorf("read: %v", err)
	}
	return nil
}

func enabled(ok bool) bool {
	if ok {
		return true
	}
	return false
}
`

	output, issues, err := Rewrite("sample.go", []byte(input))
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	got := string(output)

	for _, expected := range []string{
		"// Config ...\ntype Config struct{}",
		`return fmt.Errorf("read: %w", err)`,
		"func enabled(ok bool) bool {\n\treturn ok\n}",
	} {
		if !strings.Contains(got, expected) {
			t.Fatalf("rewritten output missing %q:\n%s", expected, got)
		}
	}

	if len(issues) != 3 {
		t.Fatalf("issues = %#v, want 3 mutation issues", issues)
	}

	wantRules := []string{"doc-stub", "error-wrap-fix", "bool-return-simplify"}
	for idx, want := range wantRules {
		if issues[idx].Rule != want || !issues[idx].Fixable {
			t.Fatalf("issue %d = %#v, want fixable %s", idx, issues[idx], want)
		}
	}
}

func TestRewriteSkipsGeneratedFiles(t *testing.T) {
	input := `// Code generated by test. DO NOT EDIT.
package sample

type Config struct{}
`

	output, issues, err := Rewrite("generated.go", []byte(input))
	if err != nil {
		t.Fatalf("Rewrite generated error = %v", err)
	}

	if string(output) != input {
		t.Fatalf("generated output changed:\n%s", output)
	}

	if len(issues) != 0 {
		t.Fatalf("issues = %#v, want none", issues)
	}
}

func TestRewriteKeepsDocumentedSymbolsAndExistingWraps(t *testing.T) {
	input := `package sample

import "fmt"

// Config stores runtime settings.
type Config struct{}

func load() error {
	if err := read(); err != nil {
		return fmt.Errorf("read: %w", err)
	}
	return nil
}
`

	output, issues, err := Rewrite("sample.go", []byte(input))
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if string(output) != input {
		t.Fatalf("output changed unexpectedly:\n%s", output)
	}

	if len(issues) != 0 {
		t.Fatalf("issues = %#v, want none", issues)
	}
}
