package readability

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRewriteAddsLogicalBlankLines(t *testing.T) {
	input := []byte(`package sample

import "sync"

var mu sync.RWMutex

func active(enabled bool, count int) bool {
	if !enabled {
		return false
	}
	if count == 0 {
		count = 1
	}
	count++
	mu.RLock()
	defer mu.RUnlock()
	for i := 0; i < count; i++ {
		if i == count-1 {
			return true
		}
	}
	return false
}
`)

	result, issues, err := Rewrite("sample.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) == 0 {
		t.Fatal("Rewrite issues = 0, want dense logical-block issues")
	}

	output := string(result)

	for _, expected := range []string{
		"return false\n\t}\n\n\tif count == 0",
		"count++\n\n\tmu.RLock()",
		"defer mu.RUnlock()\n\n\tfor i := 0",
		"\t}\n\n\treturn false",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("rewritten output missing %q:\n%s", expected, output)
		}
	}

	_, issues, err = Rewrite("sample.go", result)
	if err != nil {
		t.Fatalf("second Rewrite error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("second Rewrite issues = %#v, want none", issues)
	}
}

func TestRewriteGroupsrReadabilityLikeFunctionFlow(t *testing.T) {
	input := []byte(`package sample

import (
	"context"
	"errors"
	"strings"
	"time"
)

func build(ctx context.Context, raw string) (Result, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return Result{}, errors.New("empty")
	}
	timeout := 2 * time.Second
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	values, err := fetch(ctx, raw)
	if err != nil {
		return Result{}, err
	}
	result := Result{Name: raw, Values: values}
	result.Ready = len(values) > 0
	if !result.Ready {
		result.Reason = "empty"
	}
	_ = audit(result)
	return result, nil
}
`)

	result, issues, err := Rewrite("sample.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) == 0 {
		t.Fatal("Rewrite issues = 0, want readability grouping issues")
	}

	output := string(result)

	for _, expected := range []string{
		"raw = strings.TrimSpace(raw)\n\n\tif raw == \"\"",
		"return Result{}, errors.New(\"empty\")\n\t}\n\n\ttimeout :=",
		"ctx, cancel := context.WithTimeout(ctx, timeout)\n\tdefer cancel()\n\n\tvalues, err := fetch(ctx, raw)",
		"return Result{}, err\n\t}\n\n\tresult := Result{Name: raw, Values: values}",
		"result.Ready = len(values) > 0\n\n\tif !result.Ready",
		"result.Reason = \"empty\"\n\t}\n\n\t_ = audit(result)",
		"_ = audit(result)\n\n\treturn result, nil",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("rewritten output missing %q:\n%s", expected, output)
		}
	}

	_, issues, err = Rewrite("sample.go", result)
	if err != nil {
		t.Fatalf("second Rewrite error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("second Rewrite issues = %#v, want none", issues)
	}
}

func TestRewriteKeepsLeadingCommentsWithStatements(t *testing.T) {
	input := []byte(`package sample

func notifyLoaded() error {
	value, err := load()
	if err != nil {
		return err
	}
	// Keep this comment with the side effect.
	notify(value)
	return nil
}
`)

	result, issues, err := Rewrite("sample.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) == 0 {
		t.Fatal("Rewrite issues = 0, want comment-aware readability issue")
	}

	output := string(result)

	for _, expected := range []string{
		"return err\n\t}\n\n\t// Keep this comment with the side effect.\n\tnotify(value)",
		"notify(value)\n\n\treturn nil",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("rewritten output missing %q:\n%s", expected, output)
		}
	}

	if strings.Contains(output, "side effect.\n\n\tnotify(value)") {
		t.Fatalf("comment was separated from its statement:\n%s", output)
	}
}

func TestRewriteSkipsGeneratedFiles(t *testing.T) {
	input := []byte(`// Code generated by test. DO NOT EDIT.
package sample

func generated(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	result, issues, err := Rewrite("generated.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("Rewrite generated issues = %#v, want none", issues)
	}

	if string(result) != string(input) {
		t.Fatalf("Rewrite generated changed file:\n%s", result)
	}
}

func TestCollectFilesDeduplicatesOverlappingPaths(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "pkg", "sample.go")

	if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
		t.Fatalf("mkdir fixture: %v", err)
	}

	if err := os.WriteFile(file, []byte("package sample\n"), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	files, err := CollectFiles([]string{root, filepath.Join(root, "..."), file}, false, nil)
	if err != nil {
		t.Fatalf("CollectFiles error = %v", err)
	}

	if len(files) != 1 || files[0] != file {
		t.Fatalf("CollectFiles = %#v, want exactly %q", files, file)
	}
}
