package readability

import (
	"strings"
	"testing"
)

func TestRewriteAddsLogicalBlankLines(t *testing.T) {
	input := []byte(`package sample

import "sync"

var mu sync.RWMutex

func active(enabled bool, count int) bool {
	if !enabled {
		return false
	}
	if count == 0 {
		count = 1
	}
	count++
	mu.RLock()
	defer mu.RUnlock()
	for i := 0; i < count; i++ {
		if i == count-1 {
			return true
		}
	}
	return false
}
`)

	result, issues, err := Rewrite("sample.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) == 0 {
		t.Fatal("Rewrite issues = 0, want dense logical-block issues")
	}

	output := string(result)

	for _, expected := range []string{
		"return false\n\t}\n\n\tif count == 0",
		"count++\n\n\tmu.RLock()",
		"defer mu.RUnlock()\n\n\tfor i := 0",
		"\t}\n\n\treturn false",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("rewritten output missing %q:\n%s", expected, output)
		}
	}

	_, issues, err = Rewrite("sample.go", result)
	if err != nil {
		t.Fatalf("second Rewrite error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("second Rewrite issues = %#v, want none", issues)
	}
}

func TestRewriteSkipsGeneratedFiles(t *testing.T) {
	input := []byte(`// Code generated by test. DO NOT EDIT.
package sample

func generated(enabled bool) bool {
	if !enabled {
		return false
	}
	return true
}
`)

	result, issues, err := Rewrite("generated.go", input)
	if err != nil {
		t.Fatalf("Rewrite error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("Rewrite generated issues = %#v, want none", issues)
	}

	if string(result) != string(input) {
		t.Fatalf("Rewrite generated changed file:\n%s", result)
	}
}
