package advice

import (
	"reflect"
	"strings"
	"testing"

	"github.com/stremovskyy/go-format/internal/readability"
)

func TestAnalyzeReportsSafeOptimizationAdvice(t *testing.T) {
	source := `package sample

import (
	"context"
	"fmt"
	"regexp"
	"strings"
)

// TODO fix later
type Config struct {
	Flag bool
	Count int64
	Ready bool
}

func (c Config) name() string {
	return "config"
}

func (cfg Config) ready() bool {
	return cfg.Ready
}

func fetch(id string, ctx context.Context) error {
	if err := load(); err != nil {
		return fmt.Errorf("load: %v", err)
	}
	return nil
}

func compilePattern(raw string) *regexp.Regexp {
	return regexp.MustCompile(raw)
}

func closeAll(items []Item) {
	for _, item := range items {
		defer closeItem(item)
	}
}

func collect(items []Item) []string {
	var values []string
	for _, item := range items {
		values = append(values, item.Name)
	}
	return values
}

func render() string {
	var b strings.Builder
	b.WriteString("first")
	b.WriteString("second")
	return b.String()
}
`

	issues, err := Analyze("sample.go", []byte(source))
	if err != nil {
		t.Fatalf("Analyze error = %v", err)
	}

	want := []readability.Issue{
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "// TODO fix later"),
			Rule:    "todo-format",
			Message: "TODO should use format TODO(owner): text",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "type Config struct"),
			Rule:    "exported-doc",
			Message: "exported type Config should have a doc comment",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "Count int64"),
			Rule:    "struct-padding",
			Message: "struct Config may waste memory: field Count follows smaller field Flag",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "func (cfg Config) ready() bool"),
			Rule:    "receiver-name",
			Message: "receiver name for Config is inconsistent: saw c and cfg",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "func fetch(id string, ctx context.Context) error"),
			Rule:    "context-first",
			Message: "context.Context should be the first parameter",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, `return fmt.Errorf("load: %v", err)`),
			Rule:    "error-wrap",
			Message: "fmt.Errorf should wrap err with %w instead of %v",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "return regexp.MustCompile(raw)"),
			Rule:    "regexp-mustcompile",
			Message: "regexp.MustCompile inside function should be hoisted to package scope",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "defer closeItem(item)"),
			Rule:    "defer-in-loop",
			Message: "defer inside loop may delay cleanup until function return",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, "values = append(values, item.Name)"),
			Rule:    "append-prealloc",
			Message: "append in loop to values may need preallocation",
			Fixable: false,
		},
		{
			File:    "sample.go",
			Line:    lineOf(t, source, `b.WriteString("first")`),
			Rule:    "builder-grow",
			Message: "strings.Builder b writes string literals without Grow",
			Fixable: false,
		},
	}

	if !reflect.DeepEqual(issues, want) {
		t.Fatalf("Analyze issues mismatch\n got: %#v\nwant: %#v", issues, want)
	}
}

func TestAnalyzeSkipsGeneratedFiles(t *testing.T) {
	source := `// Code generated by test. DO NOT EDIT.
package sample

type Config struct{}
`

	issues, err := Analyze("generated.go", []byte(source))
	if err != nil {
		t.Fatalf("Analyze generated error = %v", err)
	}

	if len(issues) != 0 {
		t.Fatalf("Analyze generated issues = %#v, want none", issues)
	}
}

func lineOf(t *testing.T, source string, needle string) int {
	t.Helper()

	offset := strings.Index(source, needle)

	if offset < 0 {
		t.Fatalf("source missing %q", needle)
	}

	return strings.Count(source[:offset], "\n") + 1
}
